version: '3.1'

services:

  db_flask2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: flask_test
    ports:
      - 5431:5432